sudo: false

cache:
  directories:
    - $HOME/.composer/cache

language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install: composer update --prefer-dist --no-interaction

script: vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml
